name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/jfscraig.me
            git reset --hard
            git checkout main
            git pull
            npm install
            npm run build
            pm2 reload /var/www/jfscraig.me/hosting/ecosystem.config.js
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
